# Unix SHELL Base
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export EDITOR='vim'

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

# Development Environments

# XQuartz X11
export PATH="/opt/X11/bin:${PATH}"

# Confluent Platform
export PATH="/opt/confluent/bin:${PATH}"

# dotnet
export PATH="/usr/local/share/dotnet:${PATH}"

# LaTeX
export PATH="/Library/TeX/texbin:${PATH}"

# ccache
export PATH="/usr/local/opt/ccache/libexec:${PATH}"

# curl
export PATH="/usr/local/opt/curl/bin:${PATH}"

# perl
function perl-it () {
  if which perl > /dev/null; then
    PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
    eval "$(perl -I${HOME}/perl5/lib/perl5 -Mlocal::lib)"
  fi
}

function plenv-perl () {
  if which plenv > /dev/null; then
    eval "$(plenv init -)";
  fi
}

plenv-perl

## Ruby

### rbenv: https://github.com/rbenv/rbenv
export RBENV_ROOT=/usr/local/var/rbenv

function rbenv-ruby {
    if which rbenv > /dev/null; then
        eval "$(rbenv init -)";
    fi
}

### chef-dk: https://github.com/chef/chef-dk
function chef-dk-ruby {
    if which chef > /dev/null; then
        eval "$(chef shell-init bash)";
    fi
}

# exenv
export EXENV_ROOT=/usr/local/var/exenv
if which exenv > /dev/null; then eval "$(exenv init -)"; fi

# jenv
export JENV_ROOT=/usr/local/opt/jenv
if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# java
# export JAVA_HOME=$(/usr/libexec/java_home)

# groovy
export GROOVY_HOME="/usr/local/opt/groovy/libexec"
export GRAILS_HOME="/usr/local/opt/grails/libexec"

# golang
export GOPATH="${HOME}/Code"
export PATH="${GOPATH}/bin:/usr/local/opt/go/libexec/bin:${PATH}"

# rust
export PATH="${HOME}/.cargo/bin:${PATH}"

# nodenv
export NODENV_ROOT=/usr/local/var/nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# pyenv
export PYENV_ROOT=/usr/local/var/pyenv
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python"
export PATH="/usr/local/opt/sphinx-doc/bin:${PATH}"
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
export WORKON_HOME=~/Code/env

# sbtenv
export SBTENV_ROOT=/usr/local/var/sbtenv
if which sbtenv > /dev/null; then eval "$(sbtenv init -)"; fi

# scalaenv
export SCALAENV_ROOT=/usr/local/var/scalaenv
if which scalaenv > /dev/null; then eval "$(scalaenv init -)"; fi

# sbt
export SBT_OPTS="-XX:+CMSClassUnloadingEnabled -Xmx1024M"

# haskell-cabal
export PATH="${HOME}/.cabal/bin:${PATH}"

export MONO_GAC_PREFIX="/usr/local"

export MANPATH="/usr/local/opt/erlang/lib/erlang/man:${MANPATH}"

export PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007";'

function precmd() {
  eval "${PROMPT_COMMAND}"
}

# the fuck configuration
eval "$(thefuck --alias)"

export HOMEBREW_CASK_OPTS="--caskroom=/opt/homebrew-cask/Caskroom"

# Bash-It Configuration Home
export BASH_IT="${HOME}/.bash_it"

# Theme
export THEME_SHOW_CLOCK=true
export THEME_CLOCK_FORMAT="%H:%M:%S"
export BASH_IT_THEME='raeoks'

export GIT_HOSTING='git@github.com'

unset MAILCHECK

export IRC_CLIENT='irssi'

export SCM_CHECK=true

export SHORT_HOSTNAME=$(hostname -s)

export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source ${BASH_IT}/bash_it.sh

rbenv-ruby

export PATH=./bin:~/.bin:$PATH

source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
