#!/usr/bin/env bash -e

# Unix SHELL Base
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

# Development Environments

# dotnet
export PATH="${PATH}:/usr/local/share/dotnet"

# LaTeX
export PATH="${PATH}:/Library/TeX/texbin"

# ccache
export PATH="${PATH}:/usr/local/opt/ccache/libexec"

# perl
function perl-it () {
  if which perl > /dev/null; then
    PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
    eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
  fi
}

## Ruby

### rbenv: https://github.com/rbenv/rbenv
export RBENV_ROOT=/usr/local/var/rbenv

function rbenv-ruby {
    if which rbenv > /dev/null; then
        eval "$(rbenv init -)";
    fi
}

### chef-dk: https://github.com/chef/chef-dk
function chef-dk-ruby {
    if which chef > /dev/null; then
        eval "$(chef shell-init bash)";
    fi
}

# exenv
export EXENV_ROOT=/usr/local/var/exenv
if which exenv > /dev/null; then eval "$(exenv init -)"; fi

# # jenv
# export JENV_ROOT=/usr/local/opt/jenv
# if which jenv > /dev/null; then eval "$(jenv init -)"; fi

# java
export JAVA_HOME=$(/usr/libexec/java_home)

# golang
export GOPATH="~/Code"
export PATH="${PATH}:${GOPATH}/bin:/usr/local/opt/go/libexec/bin"

# rust
export PATH="${PATH}:${HOME}/.cargo/bin"

# nodenv
export NODENV_ROOT=/usr/local/var/nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# pyenv
export PYENV_ROOT=/usr/local/var/pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# sbtenv
export SBTENV_ROOT=/usr/local/var/sbtenv
if which sbtenv > /dev/null; then eval "$(sbtenv init -)"; fi

# scalaenv
export SCALAENV_ROOT=/usr/local/var/scalaenv
if which scalaenv > /dev/null; then eval "$(scalaenv init -)"; fi

# sbt
export SBT_OPTS="-XX:+CMSClassUnloadingEnabled -Xmx1024M"

# haskell-cabal
export PATH="${PATH}:${HOME}/.cabal/bin"

export MONO_GAC_PREFIX="/usr/local"


export MANPATH="${MANPATH}:/usr/local/opt/erlang/lib/erlang/man"

export PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007";'

precmd() {
  eval "$PROMPT_COMMAND"
}

# the fuck configuration
eval "$(thefuck --alias)"

export HOMEBREW_CASK_OPTS="--caskroom=/opt/homebrew-cask/Caskroom"

# Bash-It Configuration Home
export BASH_IT="${HOME}/.bash_it"

# Theme
export THEME_SHOW_CLOCK=true
export THEME_CLOCK_FORMAT="%H:%M:%S"
export BASH_IT_THEME='raeoks'

export GIT_HOSTING='git@github.com'

unset MAILCHECK

export IRC_CLIENT='irssi'

export SCM_CHECK=true

export SHORT_HOSTNAME=$(hostname -s)

export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source ${BASH_IT}/bash_it.sh

rbenv-ruby

export PATH=./bin:~/.bin:$PATH
